apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: {{ .Values.service.messagingPort }}
      targetPort: {{ .Values.service.messagingPort }}
      protocol: TCP
    - name: management
      port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.service.uiPort }}
      protocol: TCP
  type: ClusterIP