apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service

    # 파드에 세팅되는 컨테이너 설정
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: config-service
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}